import type { Balance } from "../live-model.ts";

export type UnlockPhase = 0 | 1 | 2 | 3;
export type SongPriority = "normal" | "high" | "top";
export type LiveBonusType = "friendship" | "speciality" | "event";

export type Song = {
  id: string;
  name: string;
  practiceBonus: string;
  liveBonus: string;
  liveBonusType: LiveBonusType;
  liveBonusValue: number;
  priority: SongPriority;
  priorityReason?: string;
  image: string;
  unlockPhase: UnlockPhase;
  cost: Balance;
};

const balance = (partial: Partial<Balance>): Balance => ({
  dance: 0,
  passion: 0,
  vocal: 0,
  visual: 0,
  mental: 0,
  ...partial,
});

export const SONGS: Song[] = [
  {
    id: "kiseki",
    name: "Believe in Miracles!",
    practiceBonus: "Wisdom training +1",
    liveBonus: "Speciality Rate +5",
    liveBonusType: "speciality",
    liveBonusValue: 5,
    priority: "normal",
    image: "assets/songs/kiseki.webp",
    unlockPhase: 0,
    cost: balance({ passion: 21, mental: 21 }),
  },
  {
    id: "tachiichi",
    name: "Zero Is Where the Center Stands!",
    practiceBonus: "Speed training +1",
    liveBonus: "Support Event Chance +1",
    liveBonusType: "event",
    liveBonusValue: 1,
    priority: "normal",
    image: "assets/songs/tachiichi.png",
    unlockPhase: 0,
    cost: balance({ dance: 21, visual: 21 }),
  },
  {
    id: "nigekiri",
    name: "Getaway! Fallin' Love",
    practiceBonus: "Guts training +1",
    liveBonus: "Support Event Chance +1",
    liveBonusType: "event",
    liveBonusValue: 1,
    priority: "normal",
    image: "assets/songs/nigekiri.png",
    unlockPhase: 0,
    cost: balance({ dance: 21, visual: 21 }),
  },
  {
    id: "go-this-way",
    name: "Go This Way",
    practiceBonus: "Power training +1",
    liveBonus: "Support Event Chance +1",
    liveBonusType: "event",
    liveBonusValue: 1,
    priority: "normal",
    image: "assets/songs/go-this-way.webp",
    unlockPhase: 0,
    cost: balance({ vocal: 21, mental: 21 }),
  },
  {
    id: "ring-ring",
    name: "Ring Ring Diary",
    practiceBonus: "Stamina training +1",
    liveBonus: "Support Event Chance +1",
    liveBonusType: "event",
    liveBonusValue: 1,
    priority: "normal",
    image: "assets/songs/ring-ring.png",
    unlockPhase: 0,
    cost: balance({ passion: 21, visual: 21 }),
  },
  {
    id: "seishun",
    name: "Here Comes Our Time",
    practiceBonus: "Power +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "+5% friendship",
    image: "assets/songs/seishun.webp",
    unlockPhase: 0,
    cost: balance({ vocal: 32, mental: 12 }),
  },
  {
    id: "run-run",
    name: "Run n' Run!",
    practiceBonus: "Skill Pts +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "SP +22 · +5% friendship",
    image: "assets/songs/run-run.webp",
    unlockPhase: 0,
    cost: balance({ dance: 14, visual: 16, mental: 14 }),
  },
  {
    id: "zensoku",
    name: "Full Speed Ahead! Umadol Power☆",
    practiceBonus: "Speed +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "+5% friendship",
    image: "assets/songs/zensoku.png",
    unlockPhase: 0,
    cost: balance({ dance: 32, visual: 12 }),
  },
  {
    id: "yume-wo-kakeru",
    name: "Run for Our Dream!",
    practiceBonus: "Skill Pt training +2",
    liveBonus: "Speciality Rate +5",
    liveBonusType: "speciality",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "SP training +2",
    image: "assets/songs/yume-wo-kakeru.webp",
    unlockPhase: 1,
    cost: balance({ passion: 21, visual: 21 }),
  },
  {
    id: "a-no-ne",
    name: "Hey, Guess What!",
    practiceBonus: "Guts training +2",
    liveBonus: "Speciality Rate +5",
    liveBonusType: "speciality",
    liveBonusValue: 5,
    priority: "normal",
    image: "assets/songs/a-no-ne.webp",
    unlockPhase: 1,
    cost: balance({ dance: 42, visual: 21 }),
  },
  {
    id: "bluebird",
    name: "Our Blue Bird Days",
    practiceBonus: "Speed training +2",
    liveBonus: "Speciality Rate +5",
    liveBonusType: "speciality",
    liveBonusValue: 5,
    priority: "normal",
    image: "assets/songs/bluebird.webp",
    unlockPhase: 1,
    cost: balance({ dance: 21, visual: 42 }),
  },
  {
    id: "grow-up-shine",
    name: "Grow Up and Shine!",
    practiceBonus: "Skill Pt training +3",
    liveBonus: "Support Event Chance +1",
    liveBonusType: "event",
    liveBonusValue: 1,
    priority: "top",
    priorityReason: "SP training +3",
    image: "assets/songs/grow-up-shine.png",
    unlockPhase: 2,
    cost: balance({ dance: 21, vocal: 21, mental: 21 }),
  },
  {
    id: "komorebi",
    name: "Sunbeam Cheer",
    practiceBonus: "Wisdom training +2",
    liveBonus: "Support Event Chance +1",
    liveBonusType: "event",
    liveBonusValue: 1,
    priority: "normal",
    image: "assets/songs/komorebi.webp",
    unlockPhase: 2,
    cost: balance({ passion: 42, mental: 21 }),
  },
  {
    id: "pyoitto",
    name: "Hoppity Sunny Days♪",
    practiceBonus: "Stamina training +2",
    liveBonus: "Speciality Rate +5",
    liveBonusType: "speciality",
    liveBonusValue: 5,
    priority: "normal",
    image: "assets/songs/pyoitto.png",
    unlockPhase: 2,
    cost: balance({ passion: 42, vocal: 21 }),
  },
  {
    id: "nanairo",
    name: "Seven Colors Scenery",
    practiceBonus: "Power training +2",
    liveBonus: "Speciality Rate +5",
    liveBonusType: "speciality",
    liveBonusValue: 5,
    priority: "normal",
    image: "assets/songs/nanairo.png",
    unlockPhase: 2,
    cost: balance({ vocal: 21, mental: 42 }),
  },
  {
    id: "yumezora",
    name: "Dream Sky",
    practiceBonus: "Wisdom +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "+5% friendship",
    image: "assets/songs/yumezora.webp",
    unlockPhase: 3,
    cost: balance({ passion: 22, mental: 22 }),
  },
  {
    id: "present-march",
    name: "Present March♪",
    practiceBonus: "Power +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "+5% friendship",
    image: "assets/songs/present-march.webp",
    unlockPhase: 3,
    cost: balance({ vocal: 22, mental: 22 }),
  },
  {
    id: "daisuki",
    name: "Precious Treasure Box",
    practiceBonus: "Speed +26",
    liveBonus: "Friendship Bonus +10%",
    liveBonusType: "friendship",
    liveBonusValue: 10,
    priority: "top",
    priorityReason: "+10% friendship",
    image: "assets/songs/daisuki.webp",
    unlockPhase: 3,
    cost: balance({ dance: 42, visual: 26 }),
  },
  {
    id: "sekai",
    name: "The World's at Our Whim",
    practiceBonus: "Stamina +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "+5% friendship",
    image: "assets/songs/sekai.webp",
    unlockPhase: 3,
    cost: balance({ passion: 32, vocal: 12 }),
  },
  {
    id: "harusora",
    name: "Sky-Blue Spring",
    practiceBonus: "Guts +22",
    liveBonus: "Friendship Bonus +5%",
    liveBonusType: "friendship",
    liveBonusValue: 5,
    priority: "high",
    priorityReason: "+5% friendship",
    image: "assets/songs/harusora.webp",
    unlockPhase: 3,
    cost: balance({ dance: 12, visual: 32 }),
  },
  {
    id: "fanfare",
    name: "Fanfare for the Future!",
    practiceBonus: "Guts +26",
    liveBonus: "Friendship Bonus +10%",
    liveBonusType: "friendship",
    liveBonusValue: 10,
    priority: "top",
    priorityReason: "+10% friendship",
    image: "assets/songs/fanfare.webp",
    unlockPhase: 3,
    cost: balance({ dance: 26, visual: 42 }),
  },
];
